apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: label-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "react-app-cluster-ip-service"
              servicePort: 3000
